# Generated by Django 3.1.3 on 2021-06-18 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='passport',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='scan_file',
            field=models.FileField(upload_to=''),
        ),
    ]
