# Generated by Django 3.1.3 on 2021-06-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210618_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='scan_file',
            field=models.FileField(upload_to='D:\\Desktop\\django\\TrawellTask\\filefolder'),
        ),
    ]
